apiVersion: intel.com/v1alpha1
kind: RmdWorkload
metadata:
  name: rmdworkload-guaranteed
spec:
  # Add fields here
  coreIds: ["0-3","6","8"]
  rdt:
    cache:
      max: 2
      min: 2
  nodes: ["silpixa00400471"] 
