apiVersion: intel.com/v1alpha1
kind: RmdWorkload
metadata:
  name: rmdworkload-guaranteed-cache-pstate
spec:
  # Add fields here
  coreIds: ["5","7"]
  cache:
    max: 2     
    min: 2
  plugins:  
    pstate:
      ratio: "3.0"
      monitoring: "on"
  nodes: ["silpixa00400471"]
